version: '3'

services:
  user-service:
    build: ./user-service
    volumes:
      - ./user-service:/code
    ports:
      - 5000:80
  room-service:
    build: ./room-service
    volumes:
      - ./room-service:/code
    ports:
      - 5001:3000
  web-client-service:
    image: nginx:alpine
    volumes:
      - ./web-client-service:/usr/share/nginx/html
    depends_on:
      - user-service
      - room-service
    ports:
      - 8000:80
